spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringCloudGuidance_Sell?characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: 123456

# mybatis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mybatis-plus:
  mapper-locations: classpath:mapping/*Mapping.xml # MyBatis Mapper 所对应的 XML 文件位置
  type-aliases-package: com.fancyliu.springcloud.product.entity

# 控制台输出 sql 语句
logging:
  level:
    com:
      fancyliu:
        springcloud:
          order:
            mapper: debug

#server:
#  port: 8081